### PR TITLE
Add coverage

### PR DESCRIPTION
**Pull request by rowleya**
This adds unit testing and coverage in the daily tests.  The coverage is split between the unit and integration tests, although the detailed view combines these.

### CODE REVIEW

**Comment by rowleya** [comment]
An example of the coverage results is seen here:
http://apollo.cs.man.ac.uk:8080/job/sPyNNaker8_Cron_Test/job/add_coverage/4/

This was the previous run, where only a single set of unit and integration tests were enabled, hence the lower than usual coverage!

The results for the latest run will be here:
http://apollo.cs.man.ac.uk:8080/job/sPyNNaker8_Cron_Test/job/add_coverage/5/

**Comment by rowleya** [comment]
Note: The "Cobertura Coverage Report" is the detailed view, and the "Coverage Reports" gives the summaries for the splitting between unit and integration tests.

**Comment by Christian-B** [comment]
Is this PR worth keeping?

**Comment by rowleya** [comment]
This is the coverage report for master at present; I think I also made this available in the IntegrationTests repository by default, so I don't mind whether we use this or that instead.

**Comment by Christian-B** [comment]
The sPyNNaker8 repository is no longer in use.

The code including test scripts has been moved to https://github.com/SpiNNakerManchester/sPyNNaker

The running of the Integration Tests has been moved to https://github.com/SpiNNakerManchester/IntegrationTests

Therefor please do one of the following.

1. Close the PR has no longer needed.

2. Move the changes to the repositories above
    Please add the label "To be merged" to indicate you will do so later.

3. Add the label "Merge help required" if you need help with the merge/move

4. Add the label "do not transfer" if you would like the PR left open as a reference only.

**Comment by rowleya** [comment]
Now done in IntegrationTests

**Pull request closed without merging**
