### PR TITLE
Citation

### PR DESCRIPTION
**Pull request by alan-stokes**
adds citation and manifest files. start point for further work on creating a doi for the tools

### CODE REVIEW

**Comment by alan-stokes** [comment]
odd dependency error. works here

**Comment by rowleya** [comment]
You need to merge in master

**Comment by alan-stokes** [comment]
na, still didnt help. if anything. it made things worse. ill merge master into all the branches. but seems weird

**Comment by alan-stokes** [comment]
ok, you win. once all in master. it worked. least its one less task to sort out.

**Comment by rowleya** [comment]
This is still giving errors in Travis.  The cause is apparently that cffconvert has a hard dependency on requests 2.20.0 but FEC has a softer dependency on requests >2.4.0 which has resulted in 2.21.0 being installed.  This is not a conflict. but the order of the installs has created a problem.  I would be interested in knowing why cffconvert has such a hard restriction however...

**Comment by rowleya** [comment]
I have submitted an issue citation-file-format/cff-converter-python#95 to attempt to resolve the conflict

**Pull request merged**
