### PR TITLE
Neuromodulation

### PR DESCRIPTION
**Pull request by mmikaitis**
Hello,

Please have a look at this code - I believe this together with the code in sPyNNaker
might be in a first mergeable version - subject to your comments and changes required.

Cheers,
Mantas

Merge with
https://github.com/SpiNNakerManchester/sPyNNaker/pull/366
https://github.com/SpiNNakerManchester/PyNN8Examples/pull/24

### CODE REVIEW

**Review by dkfellows — APPROVED** [review]
Looks fine to me _if we accept the functionality at all_.

**Review by andrewgait — APPROVED** [review]
Approved alongside comments at SpiNNakerManchester/sPyNNaker#366

**Comment by Christian-B** [comment]
The sPyNNaker8 repository is no longer in use.

The code including test scripts has been moved to https://github.com/SpiNNakerManchester/sPyNNaker

The running of the Integration Tests has been moved to https://github.com/SpiNNakerManchester/IntegrationTests

Therefor please do one of the following.

1. Close the PR has no longer needed.

2. Move the changes to the repositories above
    Please add the label "To be merged" to indicate you will do so later.

3. Add the label "Merge help required" if you need help with the merge/move

4. Add the label "do not transfer" if you would like the PR left open as a reference only.

**Comment by andrewgait** [comment]
New tests and code moved to SpiNNakerManchester/sPyNNaker#366

Now tested using https://github.com/SpiNNakerManchester/IntegrationTests/pull/8

**Pull request closed without merging**
