### PR TITLE
Fix sub timestep STDP issues

### PR DESCRIPTION
**Pull request by rowleya**
Add a new test

### CODE REVIEW

**Comment by alan-stokes** [comment]
these prs tested by determism branches says it fixes the problem..... if the code change are valid. ill leave to @andrewgait to decide.

**Comment by alan-stokes** [comment]
accordingly. ive pushed them into determism. so if you merge that you get these for free

**Comment by andrewgait** [comment]
> these prs tested by determism branches says it fixes the problem..... if the code change are valid. ill leave to @andrewgait to decide.

Looks fine to me, so happy for this to be merged / combined with determinism (whichever is easiest).

**Comment by andrewgait** [comment]
Assuming all the STDP tests still pass on this branch, of course...

**Comment by alan-stokes** [comment]
wonder why they dont pass on this branch but pass on determism.......

**Comment by rowleya** [comment]
They were passing on this branch, except for a board issue

**Comment by rowleya** [comment]
Closing as now part of #421

**Pull request closed without merging**
