### PR TITLE
More integration tests

### PR DESCRIPTION
**Pull request by Christian-B**
Depends on: https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/148
Neo Plotter 
Neo Converter
Neo Comparer

Integration Test work done

### CODE REVIEW

**Comment by Christian-B** [comment]
Review Bottom up as top stuff is tests.

**Comment by alan-stokes** [comment]
fix your errors first.

**Comment by dkfellows** [comment]
Depends on upstream branch:

- [ ] https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/154

**Comment by Christian-B** [comment]
Actually depends on 
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/tree/no_binaries_virtual_machine

**Comment by alan-stokes** [comment]
almost working. still haven't fixed this true= false aspect. which may be a numpy thing. until that's rectified. I wouldn't be prepared to put this into master yet.

**Comment by Christian-B** [comment]
I think the local copy of .../sPyNNaker8/p8_integration_tests/tests_for_param_vertex_retrieval_from_board_after_1_run/200_17_gsyn.csv
has become corrupted.
Please try reverting it and running again

**Pull request merged**
