### PR TITLE
fixed test for new named report folder

### PR DESCRIPTION
**Pull request by alan-stokes**
This is just a rename issue. but linked to the pull requests about below:

improves on SDP by at least a factor of 2 for Ethernet connected chips and up to 22 times for none ethernet connected chips. 

links to other pull requests that need to be merged in at the same time
- [ ] PACMAN: https://github.com/SpiNNakerManchester/PACMAN/pull/152
- [ ] spynnaker: https://github.com/SpiNNakerManchester/sPyNNaker/pull/482
- [ ] SPINNMan https://github.com/SpiNNakerManchester/SpiNNMan/pull/113
- [ ] SpiNNMachine https://github.com/SpiNNakerManchester/SpiNNMachine/pull/66
- [ ] FrontEndCommon: https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/295
- [ ] GFE: https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/79

### CODE REVIEW

**Comment by Christian-B** [comment]
I have run a significant number of integration test using a spin3 board and all looks good.

**Comment by Christian-B** [comment]
Is this still valid?

If yes how will it effect the Java stuff?

**Comment by dkfellows** [comment]
This PR is mostly valid. Some of what it depends on is not. I'm working on it.

**Comment by dkfellows** [comment]
This PR no longer relevant

**Comment by alan-stokes** [comment]
is the branch relevant anymore?

**Pull request closed without merging**
