### PR TITLE
Migrated setup script

### PR DESCRIPTION
**Pull request by rowleya**
Although we want PyNN to include these links eventually, having a script we can point users at does no harm

### CODE REVIEW

**Comment by alan-stokes** [comment]
well apart from when having both on the same thing. can this script be used with virtual environments?

**Comment by rowleya** [comment]
Short answer: yes
Long answer: yes, yes it can

**Comment by alan-stokes** [comment]
grand.

**Comment by rowleya** [comment]
If you have PyNN 7 installed and you call the sPyNNaker8 version of this script, it will happily destroy your environment for you.  That said, you can simply call the sPyNNaker7 version to fix it, since it also happily overwrites any existing pyNN.spinnaker.__init__.py file.

**Comment by alan-stokes** [comment]
maybe put a detection of this and warn the user that this has happened. otherwise we'll get users complaining, as they wont realise that its not compatible

**Comment by rowleya** [comment]
Agreed - if I can get it to detect.  So long as PyNN actually has an __version__ it should be possible... - will check

**Comment by rowleya** [comment]
Version check has been added (also to sPyNNaker 7)

**Pull request merged**
