### PR TITLE
Add get_spike_counts to population

### PR DESCRIPTION
**Pull request by andrewgait**
- there's probably also a way of doing this with neo objects which
  should be investigated

Related to issue https://github.com/SpiNNakerManchester/sPyNNaker/issues/414

### CODE REVIEW

**Comment by alan-stokes** [comment]
given this is a clone of the code that's in pynn 7. shouldn't we push it to spynnaker pop common and then link to it in each pop / let it be taken if the interface is the same?

**Comment by andrewgait** [comment]
That's a good idea - I'll get round to that at some point soon...

**Comment by alan-stokes** [comment]
thanks for catching the missing functionality by way. looks like pynn 08 was working by the skin of its teeth. lol

**Comment by andrewgait** [comment]
On further inspection, I think this should probably stay as it is; the sPyNNaker7 code for get_spike_counts in https://github.com/SpiNNakerManchester/sPyNNaker7/blob/master/spynnaker7/pyNN/models/pynn_population.py is slightly different in that it calls getSpikes, which is deprecated in PyNN 0.8 (and hence not called from this get_spike_counts function).  Or should the sPyNNaker7 code be changed so that it doesn't use getSpikes?

**Comment by alan-stokes** [comment]
given the spynnaker7 get spikes just checks gather and compatibile outputs that are only partly valid in get spike count, then switches the the spynnaker get_data_item. id modify spike count to call the checker with compat set to true, then use the lower interface then push directly into spynnaker. but your welcome to declare that as pointless.....

**Comment by andrewgait** [comment]
We'd need to add the "check gather and compatible outputs" to spynnaker in that case as well; it's not used in sPyNNaker8 at all at the moment.

**Comment by alan-stokes** [comment]
fair enough. at least compatible output isnt in 0.8 so you can hardcore that response. lol. or you could split it inot 2 methods, leave one in 0.75 (compatible output) and put the gather in spynnaker.

**Comment by andrewgait** [comment]
Now depends on https://github.com/SpiNNakerManchester/sPyNNaker/pull/421
Don't forget to merge https://github.com/SpiNNakerManchester/PyNN8Examples/pull/8 as well

**Pull request merged**
