### PR TITLE
Parallel examples

### PR DESCRIPTION
**Pull request by rowleya**
Try running them in parallel so I can fix what goes wrong...

### CODE REVIEW

**Comment by rowleya** [comment]
This depends on fixes to scripts in SpiNNakerManchester/PyNN8Examples#34

**Comment by Christian-B** [comment]
These changes are fine assuming script changes are fine.

**Comment by Christian-B** [comment]
We could consider adding back in some of the scripts excluded by 
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_integration_tests/scripts_test/build_script.py
lines 82 ...

**Comment by rowleya** [comment]
Trying again with this enabled...

**Comment by rowleya** [comment]
I have added in a few more of the tests; the last two more than double the time required.  This is ready to go now if you are happy with it...

**Pull request merged**
